name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Skia
      shell: bash
      run: |
        curl --ssl-revoke-best-effort -L -o "Skia-Windows-Release-x64.zip" "https://github.com"
        unzip "Skia-Windows-Release-x64.zip" -d skia
    - uses: aseprite/get-ninja@main
    - uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
    - name: Generating Makefiles
      shell: bash
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DENABLE_TESTS=OFF \
          -DENABLE_SCRIPTING=ON \
          -DENABLE_CCACHE=OFF \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$(realpath skia) \
          -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)
    - name: Compiling
      shell: bash
      run: |
        cd build && ninja aseprite
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows
        path: build/bin/
