name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Dependencies
      run: |
        choco install ninja cmake
    - name: Download Skia
      run: |
        curl -L -o skia.zip https://github.com
        expand-archive skia.zip -destinationpath C:\skia
    - name: Configure CMake
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=C:\skia -DSKIA_LIBRARY_DIR=C:\skia\out\Release-x64 -DSKIA_LIBRARY=C:\skia\out\Release-x64\skia.lib
    - name: Build Aseprite
      run: |
        cmake --build build --target aseprite
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows
        path: build/bin/
